Crypto Price Tracker
srikomm-telus/Golang-assignment-srikomm pull request #1
Opened 2023-01-31 08:04 UTC by srikomm-telus

Requirements - https://www.notion.so/playment/Golang-assignment-6e6df82a03024d9c92d44821b666001c

2023-01-31 11:22 UTC, mahendrabishnoi2 reviewed
Main issues:
* Not using dependency injection, using global variables.
* Using separate util type packages for things that should be part of packages where these are being used.
* Redis client and its usage - New connection opening and closing for each operation.
* Logging is not being done using the middleware pattern. Each request is logged manually.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +func GetCryptoPrice(cryptoName string) (CryptoPriceServiceResponse, error) {
There should be a struct for service here and these functions should be methods of the service.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +	StoredCryptoPrice, err := cryptoPriceFromCache(cryptoName)
```suggestion
	storedCryptoPrice, err := cryptoPriceFromCache(cryptoName)
```

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +	StoredCryptoPrice, err := cryptoPriceFromCache(cryptoName)
Variable names should start with Capital case only when they are not inside a function and needs to be exported.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on redis/redisClient.go
> +	rdb.ConfigureRedisClient()
Why do you need to call ConfigureRedisClient everytime this method is called?

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +	rdb := RedisClient{}
These shouldn't be accessed directly like this. You need to use dependency injection.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +	eurRate := rdb.GetValue(EU_CRYPTO_PRICE_CACHE_KEY + cryptoName)
Storage layer logic shouldn't be part of the service layer.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on util/Converter.go
> +func CoinBaseResponseToCryptoConverter(cbr CoinBaseResponse) Crypto {
IMO these should be part of the package where these are used.

2023-01-31 11:22 UTC, mahendrabishnoi2 commented on redis/redisClient.go
> +		err := client.Close()
This will seriously impact performance of application under load as you are creating and closing a connection every time this api is being called.

2023-02-12 21:40 UTC, srikomm-telus commented on client/coinDeskClient.go
> +	err = json.NewDecoder(response.Body).Decode(&coinBaseResponse)
Refactored

2023-02-12 21:45 UTC, srikomm-telus commented on client/coinDeskClient.go
> +	. "Golang-assignment-srikomm/util"
Refactored

2023-02-14 00:21 UTC, srikomm-telus commented on client/cryptonatorClient.go
> +	response, err := http.Get(CRYPTONATOR_ENDPOINT)
Refactored

2023-02-14 00:21 UTC, srikomm-telus commented on redis/redisClient.go
> +var ctx = context.Background()
Refactored

2023-02-14 00:21 UTC, srikomm-telus commented on redis/redisClient.go
> +		panic(err)
Refactored

2023-02-14 00:21 UTC, srikomm-telus commented on redis/redisClient.go
> +	rdb.ConfigureRedisClient()
Changed the implementation

2023-02-14 00:21 UTC, srikomm-telus commented on redis/redisClient.go
> +		err := client.Close()
Changed the implementation

2023-02-14 00:21 UTC, srikomm-telus commented on util/Converter.go
> +func CoinBaseResponseToCryptoConverter(cbr CoinBaseResponse) Crypto {
Refcatored

2023-03-03 04:46 UTC, mahendrabishnoi2 requested changes
@srikomm-telus Tests are pending.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +var cps CryptoPriceService
Why is this a package variable?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +	cps, err = NewCryptoPriceService(constants.DEFAULT_CRYPTO, c)
Are you going to create a new instance of service for each request?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +	cps, err = NewCryptoPriceService(constants.DEFAULT_CRYPTO, c)
DI should be used here.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +		panic(err)
Remember, no panic.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +		c.JSON(http.StatusBadRequest, gin.H{
Why StatusBadRequest? Did client try to access something that doesn't exist or sent malformed data

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +func getSpecificCryptoPriceHandler(c *gin.Context) {
All comments from above handler apply here.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +func (cps CryptoPriceService) GetCryptoPrice(cryptoName string) (models.CryptoPriceServiceResponse, error) {
use pointer receivers for service and db structs. Value receivers will use a copy of the struct, which might not be safe.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +func NewCryptoPriceService(cryptoName string, ctx context.Context) (CryptoPriceService, error) {
This doesn't seem right. What is the reasoning behind passing crypto name to constructor.

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +	if err == nil {
err == nil?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on store/redisClient.go
> +	defer rdb.client.Close()
What does this do and why do we need to do it for each get or set call?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on store/redisClient.go
> +	ctx    context.Context
Why are we storing context?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on store/cryptoCacheStorage.go
> +	err = c.storage.SetValue(constants.EU_CRYPTO_PRICE_CACHE_KEY+crypto.GetCryptoName(), crypto.GetPriceInCurrency(constants.EUR_CURRENCY_IDENTIFIER),
any reason for storing usd and eur prices separately for same krypto?

2023-03-03 04:46 UTC, mahendrabishnoi2 commented on config/config.go
> +}
This should be read from a config file.

2023-03-06 02:36 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +		c.JSON(http.StatusBadRequest, gin.H{
Refactored this to `InternalServerError`

2023-03-06 02:46 UTC, srikomm-telus commented on cryptoPriceService.go
> +func (cps CryptoPriceService) GetCryptoPrice(cryptoName string) (models.CryptoPriceServiceResponse, error) {
refactored accordingly

2023-03-06 02:47 UTC, srikomm-telus commented on cryptoPriceService.go
> +func NewCryptoPriceService(cryptoName string, ctx context.Context) (CryptoPriceService, error) {
There are multiple clients to fetch crypto price from, this will inform the constructor which client to instantiate.

2023-03-06 02:47 UTC, srikomm-telus commented on cryptoPriceService.go
> +	if err == nil {
Yes

2023-03-06 02:50 UTC, srikomm-telus commented on store/redisClient.go
> +	defer rdb.client.Close()
Forgot to remove this while making incremental changes, removed now

2023-03-06 02:50 UTC, srikomm-telus commented on store/redisClient.go
> +	ctx    context.Context
Forgot to remove this while making incremental changes, removed now

2023-03-06 03:06 UTC, srikomm-telus commented on store/cryptoCacheStorage.go
> +	err = c.storage.SetValue(constants.EU_CRYPTO_PRICE_CACHE_KEY+crypto.GetCryptoName(), crypto.GetPriceInCurrency(constants.EUR_CURRENCY_IDENTIFIER),
this happened incrementally

2023-03-06 03:24 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +		panic(err)
this was missed only in this file I guess, I've removed panics from the whole repo. Removed these as well now

2023-03-06 03:25 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +var cps CryptoPriceService
Since there aren't bean equivalents, I made it a package variable

2023-03-08 17:48 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +	cps, err = NewCryptoPriceService(constants.DEFAULT_CRYPTO, c)
Refactored accordingly (as per our offline discussion)

2023-03-08 17:48 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +func getSpecificCryptoPriceHandler(c *gin.Context) {
Addressed all of them here as well

2023-03-08 17:54 UTC, srikomm-telus commented on store/redisClient.go
> +	ctx    context.Context
Refactored and removed `context` from the struct.

2023-03-08 19:12 UTC, srikomm-telus commented on config/config.go
> +}
Refactored

2023-03-09 13:20 UTC, mahendrabishnoi2 requested changes

2023-03-09 13:20 UTC, mahendrabishnoi2 commented on cryptoPriceServiceV2.go
> +	}
Is this correct? Won't this restrict your service from using another client?
Will review rest after resolving this comment.

2023-03-09 20:59 UTC, srikomm-telus commented on cryptoPriceServiceV2.go
> +	}
Refactored, but don't if that is the best way to deal with this problem

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on main.go
> +		cpsv2            = NewCryptoPriceServiceV2(store.CryptoCacheStorage{CacheClient: redisClient})
use constructor instead of store.CryptoCacheStorage{CacheClient: redisClient}

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +func AddHttpTransport(routerGroup *gin.RouterGroup, cps CryptoPriceService, cpsv2 CryptoPriceServiceV2, ctx context.Context) {
Accept pointers to services or better accept interfaces.

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on main.go
> +	AddHttpTransport(routerGroup, *cps, *cpsv2, ctx)
Do not use pointer dereference here. This will pass a copy of service.

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +		CryptoPrice, err := cps.GetCryptoPrice(constants.BITCOIN_IDENTIFIER, ctx)
```suggestion
		cryptoPrice, err := cps.GetCryptoPrice(constants.BITCOIN_IDENTIFIER, ctx)
```

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +func AddHttpTransport(routerGroup *gin.RouterGroup, cps CryptoPriceService, cpsv2 CryptoPriceServiceV2, ctx context.Context) {
Always make context.Context first argument to a function. This comment applies to all usages like this

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +		CryptoPrice, err := cps.GetCryptoPrice(constants.BITCOIN_IDENTIFIER, ctx)
Wrong usage of context. Request context (c *gin.Context) should be passed to downstream instead of global context

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceTransport.go
> +	return func(c *gin.Context) {
Same comments as above handler

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceServiceV2.go
> +		cps.setDownstreamClient(cryptoName)
not thread safe

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on store/CryptoStorageInterface.go
> +	SetCryptoPrice(crypto models.Crypto, ctx context.Context) (bool, error)
only error is sufficient

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on cryptoPriceService.go
> +func (cps *CryptoPriceService) cryptoPriceFromDownstream() (*models.CryptoPriceServiceResponse, error) {
no need to use pointer type for return variable in this cae

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on constants/constants.go
> +var DATA = "data"
?

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on config/redisConfig.json
> +{
envrionment can be part of config instead of constants.go file

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on config/redisConfig.go
> +}
why do you need both?

2023-03-10 12:32 UTC, mahendrabishnoi2 commented on config/redisConfig.json
> +  "PRODUCTION": {
Why do you need both here? Either one should be fine depending on env

2023-03-13 20:38 UTC, srikomm-telus commented on main.go
> +		cpsv2            = NewCryptoPriceServiceV2(store.CryptoCacheStorage{CacheClient: redisClient})
refactored

2023-03-13 20:38 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +func AddHttpTransport(routerGroup *gin.RouterGroup, cps CryptoPriceService, cpsv2 CryptoPriceServiceV2, ctx context.Context) {
refactored

2023-03-13 20:39 UTC, srikomm-telus commented on main.go
> +	AddHttpTransport(routerGroup, *cps, *cpsv2, ctx)
refactored

2023-03-13 20:39 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +		CryptoPrice, err := cps.GetCryptoPrice(constants.BITCOIN_IDENTIFIER, ctx)
refactored

2023-03-13 20:50 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +func AddHttpTransport(routerGroup *gin.RouterGroup, cps CryptoPriceService, cpsv2 CryptoPriceServiceV2, ctx context.Context) {
refactored

2023-03-13 20:50 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +		CryptoPrice, err := cps.GetCryptoPrice(constants.BITCOIN_IDENTIFIER, ctx)
refactored

2023-03-13 20:50 UTC, srikomm-telus commented on cryptoPriceTransport.go
> +	return func(c *gin.Context) {
refactored

2023-03-13 20:50 UTC, srikomm-telus commented on cryptoPriceServiceV2.go
> +		cps.setDownstreamClient(cryptoName)
refactored

2023-03-13 20:51 UTC, srikomm-telus commented on store/CryptoStorageInterface.go
> +	SetCryptoPrice(crypto models.Crypto, ctx context.Context) (bool, error)
refactored

2023-03-13 20:51 UTC, srikomm-telus commented on cryptoPriceService.go
> +func (cps *CryptoPriceService) cryptoPriceFromDownstream() (*models.CryptoPriceServiceResponse, error) {
refactored

2023-03-13 20:51 UTC, srikomm-telus commented on constants/constants.go
> +var DATA = "data"
refactored

2023-03-13 21:15 UTC, srikomm-telus commented on config/redisConfig.json
> +{
I'm not sure about this

2023-03-13 21:15 UTC, srikomm-telus commented on config/redisConfig.json
> +  "PRODUCTION": {
refactored

2023-03-16 10:02 UTC, srikomm-telus commented on cryptoPriceServiceV2.go
> +		cryptoPrice, err = cps.coinDeskClient.GetBTCCurrentPrice()
this was addressed in the last commit after our offline discussion

2023-03-16 10:02 UTC, merged